### PR TITLE
Add commands JSON for easier command adding + edit of README and License

### PR DESCRIPTION
**Pull request by NguyenAndrew**
Please check the individual commits for the features added, and files changed.

If you have any questions about the README or License changes, let me know!

### CODE REVIEW

**Comment by acxroz** [comment]
Thank you, for you're Pull Request, I have had a look into the files and see what you have updated, I like the JSON idea, but I personally still have to learn how to use them! Sorry but I don't understand licenses very well, As I can see you have updated the license to only me which I don't understand. 

Regards Michael.

**Comment by NguyenAndrew** [comment]
Sure, I can explain the license for you!

If you check out your tmi.js dependency at https://github.com/acxroz/TwitchBot-GitHub-Release/tree/master/node_modules/tmi.js, it already has the license for that specific dependency (the tmi.js code). 

The code that you implement is not owned by the tmi.js people, so it makes no sense for you to put them on the license for your project. 

Hope that explains it for you. Let me know, if you have any more questions on licenses.

Btw, if you use JavaScript, you are going to be using JSON a lot, so I would definitely recommend getting familiar with it! :)

Feel free to accept the pull request, after you check over all the changes!

**Comment by acxroz** [comment]
Ok thank you!

**Comment by acxroz** [comment]
I'll assess the, contents of you're Pull Request. I'd rather, learn from you're pull request and make the project better when I get the chance, instead of just copying it over to the repo.

Thanks again!

**Comment by NguyenAndrew** [comment]
Sounds good!

**Pull request closed without merging**
